// More information about this indicator can be found at:
// http://fxcodebase.com/

//+------------------------------------------------------------------+
//|                               Copyright © 2018, Gehtsoft USA LLC | 
//|                                            http://fxcodebase.com |
//+------------------------------------------------------------------+
//|                                      Developed by : Mario Jemic  |
//|                                          mario.jemic@gmail.com   |
//+------------------------------------------------------------------+
//|                                 Support our efforts by donating  |
//|                                  Paypal : https://goo.gl/9Rj74e  |
//+------------------------------------------------------------------+
//|                                Patreon :  https://goo.gl/GdXWeN  |
//|                    BitCoin : 15VCJTLaz12Amr7adHSBtL9v8XomURo9RF  |
//|               BitCoin Cash : 1BEtS465S3Su438Kc58h2sqvVvHK9Mijtg  |
//|           Ethereum : 0x8C110cD61538fb6d7A2B47858F0c0AaBd663068D  |
//|                   LiteCoin : LLU8PSY2vsq7B9kRELLZQcKf5nJQrdeqwD  |
//+------------------------------------------------------------------+

// Effective Volume™ is an indicator developed by Pascal Willain and published in the  book "Value in Time" , Wiley 2008.
//This indicator detects institutional activities by stastistically analysing price/volume movements on the minute level.
//This analysis allows to show institutional players' activities out of the noise generated by retail players.
//More information can be found on www.effectivevolume.eu
//Effective Volume is a registered trademark.
//Adaptation of Effective Volume™ to "Wall Street" has been provided by Paul Menzing.

#property copyright "Copyright © 2018, Gehtsoft USA LLC"
#property link      "http://fxcodebase.com"
#property version   "1.0"
#property strict

#property indicator_separate_window
#property indicator_buffers 2
#property indicator_color1 Green
#property indicator_label1 "PlotLEV"
#property indicator_color2 Red
#property indicator_label2 "PlotSEV"

extern int volume_filter = 5; // VolumeFilter %
extern int price_filter = 1; // PriceFilter %
extern double smallest_price_increment = 0.01; // Smallest Price Increment
extern double Size = 0.001; // Size
extern int total_days = 15; // Total Days
extern bool multiple_days = true; // Multiple days
extern string session_close = "170000"; // Session close

double PlotLEV[], PlotSEV[], xDayCount[], TotalEffectiveVolume[], LargeEffectiveVolume[], SmallEffectiveVolume[];
double aEffectiveVolume[1440], aTmp[1440];

string IndicatorName;
string IndicatorObjPrefix;

string GenerateIndicatorName(const string target)
{
   string name = target;
   int try = 2;
   while (WindowFind(name) != -1)
   {
      name = target + " #" + IntegerToString(try++);
   }
   return name;
}

int _total_days;
int SessionEndTime;

int ParseTime(const string time, string &error)
{
   int time_parsed = (int)StringToInteger(time);
   int seconds = time_parsed % 100;
   if (seconds > 59)
   {
      error = "Incorrect number of seconds in " + time;
      return -1;
   }
   time_parsed /= 100;
   int minutes = time_parsed % 100;
   if (minutes > 59)
   {
      error = "Incorrect number of minutes in " + time;
      return -1;
   }
   time_parsed /= 100;
   int hours = time_parsed % 100;
   if (hours > 23)
   {
      error = "Incorrect number of hours in " + time;
      return -1;
   }
   return (hours * 60 + minutes) * 60 + seconds;
}

int init()
{
   IndicatorName = GenerateIndicatorName("Effective Volume");
   IndicatorObjPrefix = "__" + IndicatorName + "__";
   IndicatorShortName(IndicatorName);
   IndicatorBuffers(6);
   IndicatorDigits(Digits);
   SetIndexStyle(0, DRAW_LINE);
   SetIndexBuffer(0, PlotLEV);
   SetIndexStyle(1, DRAW_LINE);
   SetIndexBuffer(1, PlotSEV);

   SetIndexBuffer(2, xDayCount);
   SetIndexEmptyValue(2, 0.0);
   SetIndexBuffer(3, TotalEffectiveVolume);
   SetIndexEmptyValue(3, 0.0);
   SetIndexBuffer(4, LargeEffectiveVolume);
   SetIndexEmptyValue(4, 0.0);
   SetIndexBuffer(5, SmallEffectiveVolume);
   SetIndexEmptyValue(5, 0.0);
   _total_days = total_days <= 5 ? 7 : (int)((total_days / 5.0) * 7.0);
   string error;
   SessionEndTime = ParseTime(session_close, error);
   if (SessionEndTime == -1)
   {
      return INIT_FAILED;
   }
   
   return(0);
}

int deinit()
{
   ObjectsDeleteAll(ChartID(), IndicatorObjPrefix);
   return(0);
}

int start()
{
   if (Bars <= 1) 
      return 0;
   int ExtCountedBars = IndicatorCounted();
   if (ExtCountedBars < 0) 
      return -1;

   double DayCount = 0;
   int NumBars = 0;
   datetime StartDate = iTime(NULL, PERIOD_D1, 0) - (_total_days + 2) * 86400;
   int limit = Bars - 2;
   int i = limit;
   long TotalDailyVolume = 0;
   double VolumeFilter = 0;
   double TotalDailyEV = 0;
   while (i >= 0)
   {
      if (Time[i] >= StartDate)
      {
         TotalDailyVolume += Volume[i];
         if (DayCount == 0)
         {
            NumBars                 = 0;
            LargeEffectiveVolume[i] = 0;
            SmallEffectiveVolume[i] = 0;
            PlotLEV[i]              = EMPTY_VALUE;
            PlotSEV[i]              = EMPTY_VALUE;
         }
         else
         {
            NumBars++;
            double EffectiveVolume = GetEffectiveVolume(i, VolumeFilter);
            aEffectiveVolume[NumBars - 1] = EffectiveVolume;
            aTmp[NumBars - 1]             = MathAbs(EffectiveVolume);	
            TotalDailyEV += aTmp[NumBars - 1];	
         }
         long time = (Time[i] % 86400);
         long time_previous = (Time[i + 1] % 86400);
         if (time >= SessionEndTime && time_previous < SessionEndTime)
         {
            DayCount++;
            if (NumBars > 2)
            {
               SortPrices(NumBars);
               double SeparationVolume = GetSeparationVolume(NumBars, TotalDailyEV);

               for (int Counter = 0; Counter <= NumBars - 1; ++Counter)
               {
                  if (MathAbs(aEffectiveVolume[NumBars - 1 - Counter]) >= SeparationVolume)
                  {
                     LargeEffectiveVolume[i + Counter] = LargeEffectiveVolume[i + Counter + 1] + aEffectiveVolume[NumBars - 1 - Counter] * Size;
                     SmallEffectiveVolume[i + Counter] = SmallEffectiveVolume[i + Counter + 1];
                  }
                  else if (MathAbs(aEffectiveVolume[NumBars - 1 - Counter]) < SeparationVolume)
                  {
                     SmallEffectiveVolume[i + Counter] = SmallEffectiveVolume[i + Counter + 1] + aEffectiveVolume[NumBars - 1 - Counter] * Size;
                     LargeEffectiveVolume[i + Counter] = LargeEffectiveVolume[i + Counter + 1];
                  }
                  if (DayCount > 1)
                  {
                     PlotLEV[i + Counter] = MathRound(LargeEffectiveVolume[i + Counter]);
                     PlotSEV[i + Counter] = MathRound(SmallEffectiveVolume[i + Counter]);
                  }
               }

               aEffectiveVolume[NumBars - 1] = 0;
               aTmp[NumBars - 1]             = 0;
            }

            NumBars                = 0;
            VolumeFilter           = TotalDailyVolume * (volume_filter * 0.01);
            TotalDailyEV           = 0;
            TotalDailyVolume       = 0;
            TotalEffectiveVolume[i]= 0;
            if (!multiple_days)
            {
               LargeEffectiveVolume[i] = 0;
               SmallEffectiveVolume[i] = 0;	
            }
         }
      }
      i--;
   } 
   return 0;
}

void SortPrices(const int NumBars)
{
   for (int Counter1 = 0; Counter1 < NumBars - 1; ++Counter1)
   {
      for (int Counter2 = Counter1 + 1; Counter2 < NumBars; ++Counter2)
      {
         if (aTmp[Counter1] < aTmp[Counter2])
         {
            double Temp = aTmp[Counter1];
            aTmp[Counter1] = aTmp[Counter2];
            aTmp[Counter2] = Temp;
         }
      }
   }
}

double GetEffectiveVolume(const int i, const double VolumeFilter)
{
   double PriceFiter       = MathAbs(((Close[i] - Close[i + 1]) / Close[i + 1]) * 100.0);
   if (Close[i + 1] - Close[i] != 0 && Volume[i] <= VolumeFilter && PriceFiter <= price_filter)
   {
      double PriceInflection = Close[i] - Close[i + 1];
      int Direction = PriceInflection >= 0 ? 1 : -1;
      double val = MathMax(High[i], Close[i + 1]) - MathMin(Low[i], Close[i + 1]) + smallest_price_increment;
      return val == 0 ? 0 : Direction * ((MathAbs(PriceInflection) + smallest_price_increment) / val) * Volume[i];
   }
   return 0.0;
}

double GetSeparationVolume(const int NumBars, const double TotalDailyEV)
{
   int Loop = 0;
   double SeperationNumber = TotalDailyEV;
   double xMidPoint = TotalDailyEV * 0.5;
   double SeparationVolume = 0.0;
   while (Loop < NumBars && SeperationNumber >= xMidPoint)
   {
      SeperationNumber -= aTmp[Loop];	
      SeparationVolume = aTmp[Loop];
      ++Loop;
   }
   return SeparationVolume;
}
